[project]
name = "jajal-rag-tesis"
version = "0.1.0"
description = "Jajal RAG Informasi Tesis"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pypdf2>=3.0.1",
    "openai>=1.53.0",
    "numpy>=2.1.2",
    "python-dotenv>=1.0.1",
]
